name: gold_pipelines
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.0.1
  - h5py=3.8.0
  - python-graphviz=0.20.1
  - matplotlib
  - numpy>=1.19
  - faiss-cpu=1.7.4
  - zarr
  - joblib
  - tqdm
  - xarray
  - scikit-learn
  - hdbscan
  - networkx
  - pybind11
  - loky
  - numba
  - jupyter
  - ipywidgets
  - ipympl
  - pyqt=5
  - pyqtwebengine=5
  - pyqtgraph
  # If ephyviewer is available on conda-forge, use it here:
  # - ephyviewer
  - pyyaml=6.0
  - pyzmq=25.1.1
  - docker-py=6.1.3
  - pandas=2.1.1
  - scipy
  # For spikeinterface, use pip (conda-forge is often behind)
  - pip:
    - MEArec
    - PyQt5==5.15.11
    - pydantic
    - git+https://github.com/SpikeInterface/spikeinterface.git # currently 0.103.1, otherwise do spikeinterface[full,widgets]
    - spikeinterface-gui
    - mountainsort5 # or other sorters you plan to use
    - Kilosort[gui]==4.0.31
    - open-ephys-python-tools==0.1.8
    - git+https://github.com/lwthompson2/pyramid.git